name: meeting_note
description: A multi-model real-time meeting recording system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  dio: ^5.0.3
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  pdf: ^3.10.4
  share_plus: ^12.0.0
  web_socket_channel: ^3.0.3
  uuid: ^4.0.0
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/database/

  plugin:
    platforms:
      android:
        package: com.example.meeting_note
        pluginClass: AudioCapturerPlugin
      ios:
        pluginClass: AudioCapturerPlugin
      linux:
        pluginClass: AudioCapturerPlugin