name: Build Debug Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web Debug
        run: flutter build web --debug

      - name: Archive Web Debug
        uses: actions/upload-artifact@v4
        with:
          name: web-debug
          path: build/web/

  build-linux-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libgl1-mesa-dev

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Linux Debug
        run: flutter build linux --debug

      - name: Archive Linux Debug
        uses: actions/upload-artifact@v4
        with:
          name: linux-debug
          path: build/linux/x64/debug/bundle/

  build-windows-debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Debug
        run: flutter build windows --debug

      - name: Archive Windows Debug
        uses: actions/upload-artifact@v4
        with:
          name: windows-debug
          path: build/windows/x64/runner/Debug/

  build-macos-debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS Debug
        run: flutter build macos --debug

      - name: Archive macOS Debug
        uses: actions/upload-artifact@v4
        with:
          name: macos-debug
          path: build/macos/Build/Products/Debug/

  build-android-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android Debug
        run: flutter build apk --debug

      - name: Archive Android Debug
        uses: actions/upload-artifact@v4
        with:
          name: android-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

  build-ios-debug:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Debug
        run: flutter build ios --debug --no-codesign

      - name: Archive iOS Debug
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug
          path: build/ios/iphonesimulator/Runner.app