name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --debug

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Install CocoaPods
        run: |
          cd ios
          pod repo add tsinghua https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git
          pod install
      - name: Build iOS
        run: flutter build ios --debug --simulator --no-codesign